### ISSUE TITLE
Honey variant?

### ISSUE THREAD

**Issue by K0-RR** [DanikingMC/ThrowableTorch#1]
Would be great to have it alongside slime, clay, and magma ones. Since honey blocks have the same properties as slime blocks this makes sense.

**Comment by DanikingMC** [comment]
Thanks for asking! And yes, I'm going to get to work on a throwable honey variant. If you have any other questions or suggestions, just tell me!

**Comment by DanikingMC** [comment]
> Would be great to have it alongside slime, clay, and magma ones. Since honey blocks have the same properties as slime blocks this makes sense.
