### ISSUE TITLE
Texture change proposal

### ISSUE THREAD

**Issue by K0-RR** [DanikingMC/ThrowableTorch#2]
Wouldn't it be better like this or this? These examples were done quick and are just to explain what I mean by "make the torch disappear inside a {slimeball, clay ball, magma ball} or sacrifice some consistency with manga and clay "balls" and make the slime ball and honey ball semi-transparent as they should be.

![image](https://user-images.githubusercontent.com/43277609/109284101-c6d37c00-781f-11eb-9494-179c324c1617.png)

![image](https://user-images.githubusercontent.com/43277609/109284700-6db81800-7820-11eb-9a98-d9cf3abcc4e8.png)

**Comment by DanikingMC** [comment]
Take a look to the newest version of the mod
