### ISSUE TITLE
Bug: throwable torches and hoppers

### ISSUE THREAD

**Issue by MeeniMc** [DanikingMC/ThrowableTorch#3]
# Bug 1: torches can be attached on hoppers

## Steps to replicate:
1. make a floor of hoppers over another layer of solid blocks
2. throw a throwable torch toward that floor
3. the torch will attach on top of the hopper

## Expected behavior: 
In vanilla, it is not possible to attach a torch on a hopper (and probably other tile entities of the same sort). The torch should convert to item form? 

# Bug 2: torches sometimes **REPLACE** the hopper

## Steps to replicate: 
1. make a floor of hoppers over another layer of solid blocks
2. throw a throwable torch on that floor (lobbing)
3. the torch will sometimes (rare) **REPLACE** the hopper

## Expected behavior: 
The torch should obviously not destructively replace the hopper. The torch should convert to item form?

**Comment by DanikingMC** [comment]
I fixed it
